### ISSUE TITLE
Decide how to execute reconfiguration

### ISSUE THREAD

**Issue by chcorbato** [rosin-project/mros1_reasoner#11]
Can be based on:
-  [`cheops_graph_manipulation`](https://github.com/rosin-project/cheops/tree/master/cheops_graph_manipulation)
- the one from Rainbow
- Carlos' previous [metacontroller](https://github.com/chcorbato/om_ros/tree/master/OMRosDrivers_py)

- [ ] Implementation in https://github.com/rosin-project/metacontrol_sim/issues/7

**Comment by chcorbato** [comment]
@marioney can you copy here the links to the rainbow code for this?

**Comment by marioney** [comment]
> @marioney can you copy here the links to the rainbow code for this?

The code used by rainbow is this  

https://github.com/cmu-mars/cmu-robotics/blob/development/cp-gazebo-p2/cp_gazebo/scripts/kill_bringup_amcl.py

**Comment by chcorbato** [comment]
Proposal:
- implement component `Rosgraph_manipulator`
- see specification of interfaces in [architecture gdoc](https://docs.google.com/document/d/1BaOxo7_WQ2fUUUWIyw5pE_K_q6sErQJXge5VeFjyhgQ/edit#heading=h.qljntcabvb0p)

It is based on [`cheops_graph_manipulation`](https://github.com/rosin-project/cheops/tree/master/cheops_graph_manipulation) but:
- action goal is a string with the name of the desired configuration
- we need to remove the previous configuration (to decide how)
