### ISSUE TITLE
runtime error missing 'java'

### ISSUE THREAD

**Issue by chcorbato** [rosin-project/mros1_reasoner#15]
This seems related to missing dependencies related to owl reasoning #14 
Maybe just install Protege is a workaround.

**Comment by marioney** [comment]
I've solved the missing dependency by installing openjdk-11 

```
sudo apt-get install openjdk-11-jdk

```
But I'm not sure if only the jre is needed

**Comment by chcorbato** [comment]
Did you added this to the README @marioney ? If so we can close the issue I think

**Comment by chcorbato** [comment]
solved in [`mvp`](https://github.com/rosin-project/mros1_reasoner/tree/mvp)
