### ISSUE TITLE
Adaptation is not triggered with qa individuals

### ISSUE THREAD

**Issue by chcorbato** [rosin-project/mros1_reasoner#25]
The rule in `tomasys.owl` is:
**if** `fg.qa.value` **<** `obj.nfr.value`
**then** `obj` in `INTERNAL_ERROR`

`nfr.value` = 1.5 https://github.com/rosin-project/mros1_reasoner/blob/382f4a0fae4233aaf79ff3a876cd8cc508d58bbe/mros1_reasoner/scripts/init_models.py#L49

updated QA energy values for fg (* for those above nfr value):
FG Statuses:
`fg_nav_fast      None    [('obs_energy_1', '0.20000000298'), ('obs_energy_2', '**1.89199912548**'), ('obs_energy_3', '1.41609191895'), ('obs_energy_4', '1.42725098133'), ('obs_energy_5', '1.43280863762'), ('obs_energy_6', '1.43841362'), ('obs_energy_7', '1.45673406124'), ('obs_energy_8', '1.45814871788'), ('obs_energy_9', '1.45667350292'), ('obs_energy_10', '1.45740365982'), ('obs_energy_11', '1.45468640327'), ('obs_energy_12', '1.45513892174'), ('obs_energy_13', '1.45447206497'), ('obs_energy_14', '1.45391464233'), ('obs_energy_15', '1.45491302013'), ('obs_energy_16', '1.4551589489'), ('obs_energy_17', '1.45762276649'), ('obs_energy_18', '1.45493543148'), ('obs_energy_19', '1.45621967316'), ('obs_energy_20', '1.45462548733'), ('obs_energy_21', '1.45513737202'), ('obs_energy_22', '1.45356249809'), ('obs_energy_23', '1.4541246891'), ('obs_energy_24', '1.45473957062'), ('obs_energy_25', '1.45236492157'), ('obs_energy_26', '**1.68376469612**'), ('obs_energy_27', '**1.68711805344**')]`

Potential causes of the undesired behavior:
- [x] Problem with data types updating the KB
- [ ] Problem the SWRL rule QA1 in `tomasys`
   - [ ] Values need to be normalized for :
```
0  - worst case value
1  - desired value
```

**Comment by chcorbato** [comment]
There is no problem, it is simply that the rule is

**if** `fg.qa.value` **<** `obj.nfr.value`
**then** `obj` in `ERROR`


However, the values coming from diagnostics need to be **normalized**
```
0  - worst case value
1  - desired value
```

**Comment by chcorbato** [comment]
@darkobozhinoski are you finally going to normalize safety and energy QA Observations?
I am not sure whether you do it in the `Observer` or I do it in the `mros1_reasoner`

**Comment by darkobozhinoski** [comment]
@chcorbato I can do it. Is it ok to normalize according to the following formula:
0.9*normalized_current_speed+0.1_normalized_control_frequency?
Same formula I am using to calculate energy in the configuration space.

**Comment by chcorbato** [comment]
That is ok.
For the moment I did not implement top-bottom thresholds semantics in `tomasys`, but simply added a case for the `energy` and `safety` cases in the selection of configurations in mros1_reasoner.py
https://github.com/rosin-project/mros1_reasoner/blob/5263ad6da4a7507754caf6dbf0068e774c223b65/mros1_reasoner/scripts/mros1_reasoner.py#L97-L102
