### ISSUE TITLE
desired_configuration needs to be sync between metacontrol nodes

### ISSUE THREAD

**Issue by chcorbato** [rosin-project/mros1_reasoner#28]
The metacontrol MAPE-K elements need to sync on what is the desired configuration at each time:
- [x] `ros_graph_parser` (and [`rosgraph_monitor`](https://github.com/rosin-project/rosgraph_monitor)? ) use it to know what .rossystem to compare with the one extracted from the rosgraph => not needed now, see [below](https://github.com/rosin-project/mros1_reasoner/issues/28#issuecomment-631580645)
- [ ] [`mros1_reasoner`](https://github.com/rosin-project/mros1_reasoner/blob/master/mros1_reasoner/scripts/mros1_reasoner.py) needs to initialize what is the initial configuration, so it can assign the current QA values and configuration diagnostics from monitoring to it `desired_configuration`
  - [x] done on the `mros1_reasoner.py` side https://github.com/rosin-project/mros1_reasoner/blob/31def16da53deea7377f6c950c53a0462f82897b/mros1_reasoner/scripts/mros1_reasoner.py#L316
  - [ ] https://github.com/rosin-project/metacontrol_experiments/issues/8
- [x] [`rosgraph_manipulator.py`](https://github.com/rosin-project/metacontrol_sim/blob/ae7ff41e65bfa2fcf1fa101e5ee3e99f92c597bb/scripts/rosgraph_manipulator.py#L100-L117) receives it to select which configuration to deploy
=>This one is done via the [`MvpReconfiguration`](https://github.com/rosin-project/metacontrol_msgs/blob/master/action/MvpReconfiguration.action#L12) action goal received from `mros1_reasoner`

I propose to use a ROS global parameter to sync this value and also to initialize it.
What do you think @ipa-nhg @ipa-hsd @marioney

**Comment by ipa-nhg** [comment]
to me the best solution will be to set a new parameter to publish (from the metacontrol, right?) the new desired configuration. For example:

`rosparam set /current_configuration "f1_v1_r1" ` 
(obviously from code and not from command line)



>     * `ros_graph_parser` (and [`rosgraph_monitor`](https://github.com/rosin-project/rosgraph_monitor)? ) use it to know what .rossystem to compare with the one extracted from the rosgraph

Here is not needed. We can't modify dynamically the `desired.rossystem` that the `rosgraph_monitor` takes as input. The main purpose of the `rosgraph_monitor` for this models experiment is verify that all the required nodes to run my application are up. The current desired.rossystem looks -> https://github.com/rosin-project/rosgraph_monitor/blob/observers/resources/metacontrol_desired.rossystem

**Comment by chcorbato** [comment]
> We can't modify dynamically the `desired.rossystem` that the `rosgraph_monitor` takes as input. The main purpose of the `rosgraph_monitor` for this models experiment is verify that all the required nodes to run my application are up.

For the immediate future, I am very interested in being able to change it dynamically, in order for the metacontrol to manage the nodes on the fly, have a dynamic rosgraph (e.g. kill and launch new nodes as required by the mission goals)

**Comment by chcorbato** [comment]
> to me the best solution will be to set a new parameter to publish (from the metacontrol, right?) the new desired configuration. For example:
> 
> `rosparam set /current_configuration "f1_v1_r1" `
> (obviously from code and not from command line)

Agreed! I think we should name that rosparam `desired_configuration`, so as not to confuse it with the one the rosgraph_parser generates
- [ ] @marioney has an issue for metacontrol_experiments
- [ ] @chcorbato needs to do it for `mros1_reasoner`

**Comment by chcorbato** [comment]
Since it is under control and there is one issue that will finalize the implementation of this, I close this "design issue"
