### ISSUE TITLE
RECONFIGURATION UNKNOWN issue running single exp script WITH metacontrol

### ISSUE THREAD

**Issue by chcorbato** [rosin-project/mros1_reasoner#39]
`mros1_reasoner` in 353c3bebab9e0a08e8a9d891e78f8f87dfe2ba0e

Command executed:
`./run_single_sim.sh -i 2 -g 2 -n standard -r true -p 1.3
`

```
INFO] [1590138841.922033]:   >> Finished MAPE-K ** EXECUTION **
== RECONFIGURATION UNKNOWN ==
```

**Comment by chcorbato** [comment]
@marioney is there a way to preserve the terminal running `mros1_reasoner` so as to debug this more easily?

**Comment by marioney** [comment]
Sure Just add an sleep command before the `exit` in the ./run_single_sim.sh
```
if [ "$launch_reconfiguration" = true ] ; then
	echo "Launching: mros reasoner"
	gnome-terminal --window --geometry=80x24+10+10 -- bash -c "source $PYTHON3_VENV_PATH/venv3.6_ros/bin/activate;
	source $PYTHON3_VENV_PATH/devel/setup.bash;
	source $REASONER_WS_PATH/devel/setup.bash;
	roslaunch mros1_reasoner run.launch onto:=mvp.owl;
        sleep 20;
	exit"
fi
```

**Comment by chcorbato** [comment]
This has been solved now that all info is automatically loaded from the rossystem files, 
- `mros1_reasoner` the autogen ontology file
- `rosgraph_manipulator` the autogen yaml file
