### ISSUE TITLE
Add rospy.logerror() messages in mros1_reasoner to chatch debug info in log files

### ISSUE THREAD

**Issue by chcorbato** [rosin-project/mros1_reasoner#45]

**Comment by chcorbato** [comment]
Done d917ff35cd5647e7a3d3410dea2ea7f70c28ffc2

**Comment by marioney** [comment]
Also solved from `metacontrol_experiments` in https://github.com/rosin-project/metacontrol_experiments/commit/475706766a58d5dfe8be953b4e66e5aafabcd3ea
