### ISSUE TITLE
Reasoning error

### ISSUE THREAD

**Issue by chcorbato** [rosin-project/mros1_reasoner#48]
Something did not go well, probably inconsistency in the ontology.
When this error is triggered I'm saving the ontology in `~/.ros/error.owl`, so I will inspect it with Protege to check what happened.

### TEST
```
run_single_sim.sh -i 1 -g 1 -n f1_v3_r1 -r true
```

### OUTPUT
```
...
[ERROR] [1590235376.721149]: Reasoning error:
...
```

**Comment by chcorbato** [comment]
> When this error is triggered I'm saving the ontology in `~/.ros/error.owl`, so I will inspect it with Protege to check what happened.

The ontology is coherent and consistent, so I'll need to check what is happening with the reasoning
:worried: 
![Screenshot from 2020-05-23 14-15-38](https://user-images.githubusercontent.com/9592617/82730442-01900d00-9d00-11ea-922e-8471237e8e11.png)

**Comment by chcorbato** [comment]
It could be due to the `callbackDiagnostics` iasserting new facts during reasoning in `timer_cb`
Maybe we can live with this problem, since the wellformedness of the ontology does not seem affected (see previous comment)

Some additional **OUTPUT** that can be relevant:
```
ERROR] [1590236368.127794]: = RECONFIGURATION SUCCEEDED =
[INFO] [1590236368.131871]: Exited timer_cb for metacontrol reasoning
[INFO] [1590236368.141647]: Entered timer_cb for metacontrol reasoning
[INFO] [1590236368.146012]:   >> Started MAPE-K ** Analysis (ontological reasoning) **
* Owlready2 * Running Pellet...
...
[INFO] [1590236368.368852]: received QA observation
ERROR: FG not found
[INFO] [1590236368.377154]: received QA observation
ERROR: FG not found
[INFO] [1590236369.053949]: received QA observation
ERROR: FG not found
[INFO] [1590236369.060824]: received QA observation
ERROR: FG not found
[INFO] [1590236369.070854]: received QA observation
ERROR: FG not found
[INFO] [1590236369.596342]: received QA observation
ERROR: FG not found
[INFO] [1590236370.137616]: received QA observation
ERROR: FG not found
[INFO] [1590236370.143824]: received QA observation
ERROR: FG not found
[INFO] [1590236370.747393]: received QA observation
ERROR: FG not found
[INFO] [1590236371.426202]: received QA observation
ERROR: FG not found
[INFO] [1590236371.437687]: received QA observation
ERROR: FG not found <--------------------------------------------------------------------------
[ERROR] [1590236371.854689]: Reasoning error: <--------------------------------------
[INFO] [1590236371.868696]:      >> Finished ontological reasoning)
```

**Comment by chcorbato** [comment]
The problem is that I'm asserting a new FG with a name that cannot be mapped to incoming QA diagnostics:
```
[INFO] [1590236963.642090]:      >> Finished ontological reasoning)

FGs:
fg_new 	objective:  kb.o_navigateA 	status:  None 	FD:  kb.f1_v1_r3 	QAvalues:  []
```

**Comment by gavanderhoorn** [comment]
> It could be due to the `callbackDiagnostics` iasserting new facts during reasoning in `timer_cb`

that would be concurrent write access to shared resource. As `rospy` uses separate threads for timers and subscriptions, either use a (lockless) queue or properly write-lock the shared resource.

**Comment by marioney** [comment]
I've added a `lock` for the resource on https://github.com/rosin-project/mros1_reasoner/pull/52/commits/8cba195175fadc5ad56ba822b7373901a94599fe

**Comment by chcorbato** [comment]
> I've added a `lock` for the resource on [8cba195](https://github.com/rosin-project/mros1_reasoner/commit/8cba195175fadc5ad56ba822b7373901a94599fe)

It seems to solve the issue for me. I closed it.
