### ISSUE TITLE
Don't overlay Py2 workspace on Py3 (as suggested in the readme)

### ISSUE THREAD

**Issue by gavanderhoorn** [rosin-project/mros1_reasoner#5]
The [readme](https://github.com/rosin-project/mros1_reasoner/blob/7c76d6045d2e6e4c3574371c468ce43f13e7f1cf/README.md) currently states:

> Since `mros1_reasoner` depends on `cheops_system_state_msgs`, you will need [workspace overlaying](http://wiki.ros.org/catkin/Tutorials/workspace_overlaying) to run `mros1_reasoner`. You can do the following:
> ```
> source abb_cheops_ws/cheops/devel/setup.bash
> cd abb_metacontrol_ws
> catkin b
> ```

this is not a good idea, as this would overlay a Python 2 workspace on top of a Python 3 workspace.

Suggestion: copy the `cheops_system_state_msgs` package (and *just* that package) into the Python 3 workspace (ie: `abb_metacontrol_ws`), so it now exists in both the Python 2 as well as the Python 3 workspaces.

That is completely fine and supported.

In essence the Python 2 and Python 3 workspaces are completely separate ROS installations. They may even be run on different machines (but they just happen to run on the same machine).

**Comment by chcorbato** [comment]
Ok!
