### ISSUE TITLE
Define the scenario for energy:

### ISSUE THREAD

**Issue by chcorbato** [rosin-project/mros1_reasoner#9]
- what is the navigation mission
  - navigate from A to B
- what is the adaptation trigger?
  - battery consumption gets higher than a threshold 
- what is the adaptation?
  - the metacontrol reconfigures `move_base` to the [`low_power` config](https://docs.google.com/spreadsheets/d/12aB35Jj4qmarIq3OWHocATmnDfUa6ftp_j09W5twy1g/edit#gid=0&range=E2)
  - FDs only involve change in [`move_base` params `max_vel` and `max_accel`](https://docs.google.com/spreadsheets/d/12aB35Jj4qmarIq3OWHocATmnDfUa6ftp_j09W5twy1g/edit#gid=0&range=A10:G11)

**Comment by chcorbato** [comment]
- [ ] Define constants for the battery
- [ ] Define A and B

**Comment by marioney** [comment]
>     * Define constants for the battery


https://docs.google.com/spreadsheets/d/12aB35Jj4qmarIq3OWHocATmnDfUa6ftp_j09W5twy1g/edit#gid=0

**Comment by marioney** [comment]
> * Define A and B

Possible initial Values:  A =  0, 0 (center of the map)
                                     B =   10.5, 5.5  (Exit point)

![Init_goal_points](https://user-images.githubusercontent.com/5198223/80602940-0e3a8180-8a30-11ea-8d42-b032d8fa5a6e.png)

**Comment by marioney** [comment]
The following values are used to control the battery load cont
```
const_linear_vel = 1.3
const_acceleration = 0.1
const_frequency = 0.04
additional_consumption = 0.0 

```
With these values, the average power load while running the navigation is
```
safe configuration ~= 0.99
standard configuration ~= 1.45
fast configuration ~= 1.99
```
The `additional_consumption` parameter can be used to artificially increase the power load

**Comment by marioney** [comment]
The battery constants have been added to the battery power load controller  (see https://github.com/rosin-project/metacontrol_sim/pull/9#issue-410812757)
